### ISSUE TITLE
add SpinApp example

### ISSUE THREAD

**Issue by michelleN** [michelleN/spin-redis-example#1]
```
apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: redis
spec:
  image: "ghcr.io/michellen/spin-redis-rust:0.2.0"
  imagePullSecrets:
    - name: "ghcr"
  executor: containerd-shim-spin
  replicas: 1
  variables:
    - name: redis_password
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: password
    - name: redis_host
      valueFrom:
        secretKeyRef:
          name: redis-secret
          key: host
```
